name: My Self-Hosted Workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache wheels directory
      - name: Cache wheels
        uses: actions/cache@v4
        with:
          path: wheels
          key: tensorflow-wheels-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Set up Python venv
        run: |
          python3 -m venv gh-runner
          source gh-runner/bin/activate
          python -m pip install --upgrade pip setuptools wheel

          # Install TensorFlow from cached wheel or download if missing
          if [ ! -f wheels/tensorflow*whl ]; then
            echo "Downloading TensorFlow wheel..."
            pip download tensorflow-macos==2.19.0 --dest wheels
          fi

          # Install TensorFlow from local wheels folder
          pip install tensorflow-macos==2.19.0 --find-links=./wheels

          # Install remaining requirements (but skip tensorflow to avoid re-fetching)
          pip install -r <(grep -v 'tensorflow' requirements.txt)

      - name: Run tests
        run: |
          source gh-runner/bin/activate
          pytest --junit-xml=report.xml
