    name: My Self-Hosted Workflow

    on: [push]

    jobs:
      build:
        runs-on: self-hosted # or a custom label like 'my-linux-runner'
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Run custom script
            run: |
              ollama --version
              python3 -m venv gh-runner
              source gh-runner/bin/activate
              which python
              python --version
              python -m pip install --upgrade pip setuptools wheel
              pip --version
              pip install -r requirements.txt
              pytest --junit-xml=report.xml