name: My Self-Hosted Workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python venv (Rosetta if macOS ARM)
        run: |
          if [[ "$(uname)" == "Darwin" && "$(uname -m)" == "arm64" ]]; then
            echo "Apple Silicon detected — running under Rosetta"
            arch -x86_64 /usr/bin/python3 -m venv gh-runner
            source gh-runner/bin/activate
            arch -x86_64 python -m pip install --upgrade pip setuptools wheel
          else
            python3 -m venv gh-runner
            source gh-runner/bin/activate
            python -m pip install --upgrade pip setuptools wheel
          fi

      - name: Install dependencies (prefer local wheels)
        run: |
        source gh-runner/bin/activate
        pip install --no-index --find-links=$HOME/wheels -r requirements.txt || \
        pip install --find-links=$HOME/wheels --index-url=https://pypi.org/simple -r requirements.txt

      - name: Run tests
        run: |
          source gh-runner/bin/activate
          pytest --junit-xml=report.xml
